---
apiVersion: v1
kind: Deployment
metadata:
  name: javaapp-deployment
  labels:
    app: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: javaapp-container
        image: devopshint/my-app-1.0
        ports:
        - containerPort: 8080
---
  apiVersion: v1
kind: Service
metadata:
  name: javaapp-service
  labels:
    app: java-app
spec:
  selector:
    app: java-app
  type: LoadBalancer    
  ports:
  - port: 80
    targetPort: 8080 